SAUDACAO: MACRO
    OUTPUT MENSAGEM_BEMVINDO
ENDMACRO

SOMA_E_GUARDA: MACRO &DEST, &VALOR1, &VALOR2
    LOAD &VALOR1
    ADD &VALOR2+0 ; teste de normalizacao
    STORE &DEST
ENDMACRO

INICIO: SAUDACAO 

    SOMA_E_GUARDA RESULTADO, VAR1,VAR2-5

DEPOIS:  SOMA_E_GUARDA OUTRO_RES, A, B ; teste completo

ROTULO_SOZINHO:
    STOP ; Fim do programa

MENSAGEM_BEMVINDO: CONST 100
RESULTADO: SPACE
VAR1: CONST 10
VAR2: CONST 20
OUTRO_RES: SPACE
A: CONST 1
B: CONST 2